### ISSUE TITLE
Frame Serialization and Deserialization calls need optimization

### ISSUE THREAD

**Issue by Json-x-ly** [youar/upm-xrremote#1]
The amount of data being sent over the socket connection leaves plenty of performance on the table in the name of convenience. We could probably improve the performance impact on both the remote and editor by slimming down the info we pack to precisely the information we need to reconstruct the data as opposed to the current implementation which has us packaging the entire memory footprint of the Texture2D, Pose, etc. objects.

**Comment by gblikas** [comment]
Closed by #29
