### ISSUE TITLE
Camera data not sent back to Unity

### ISSUE THREAD

**Issue by duc55** [youar/upm-xrremote#15]
**Describe the bug**
XR Remote connects to phone but does not send camera data back to Unity.

**To Reproduce**
1. Created a simple AR project
	a. Start a new project using the AR template in Unity 2020.3.36f1
	b. Set platform to Android in Build Settings
	c. Go to player settings then set override package name, minimum API level at API level 24, Scripting backend to IL2CPP, and target architectures to ARMv7 and ARM64
	d. In XR Plug-in Management, enable ARCore in Plug-in providers
	e. Set AR Camera in the AR Session Origin game object to MainCamera and made sure it had the Tracked Pose Driver component.
	f. Add Sphere at (0, 0, 2) for testing
	g. On phone, enable developer mode and USB debbuging
	h. Connect phone to PC using usb and click Build and Run
	i. In Package Manager, install AR Foundation 4.1.12, ARKit XR Plugin 4.1.12, ARCore XR Plugin 4.1.12
	j. Project runs on phone

2. Install xr-remote app on phone using upm-xrremote.apk

3. Followed readme to import xr-remote package into Unity
	a. Download zip form github
	b. Using 7zip to make tarball from Assets folder
	c. Remove UIRemoteClient.cs.meta from Runtime/Scripts/RemoteView/
	d. Add XR_Remote Connection prefab to scene

4. Started app on phone
	a. Enter the phones IP into the XR Editor Client

5. Play on Unity
	a. Push Start XR Remote Session in Game window

6. App connects but only seeing a white screen in Unity.
	a. Phone reports XRRemoteServer.cs connected and AR Session: Initialized
	b. In Unity console, message reads Client 10.0.0.179 connection event incoming

**Expected behavior**
Camera data should appear in Game window.

**Screenshots**
![image](https://user-images.githubusercontent.com/67300046/221681538-340d7b1d-9758-427e-b537-effce1cbf292.png)

Error for logcat in Android Studio:
2023-02-27 12:45:35.187 24204-24226/? E/Unity: NullReferenceException: Object reference not set to an instance of an object.
      at XRRemote.Pose.op_Implicit (UnityEngine.XR.ARFoundation.ARPoseDriver arPoseDriver) [0x00000] in <00000000000000000000000000000000>:0 
      at XRRemote.XRRemoteServer.OnARCameraFrameReceived (UnityEngine.XR.ARFoundation.ARCameraFrameEventArgs obj) [0x00000] in <00000000000000000000000000000000>:0 
      at System.Action`1[T].Invoke (T obj) [0x00000] in <00000000000000000000000000000000>:0 
      at UnityEngine.XR.ARFoundation.ARCameraManager.InvokeFrameReceivedEvent (UnityEngine.XR.ARSubsystems.XRCameraFrame frame) [0x00000] in <00000000000000000000000000000000>:0 
      at UnityEngine.XR.ARFoundation.ARCameraManager.Update () [0x00000] in <00000000000000000000000000000000>:0 

**Desktop (please complete the following information):**
 - OS:Window 10 64-bit

**Smartphone (please complete the following information):**
 - Device: Motorola Moto G Power
 - OS: Android 11
 - 

**Additional context**

**Comment by gblikas** [comment]
Hey @duc55, thanks for the bug report! We'll look into this.

**Comment by duc55** [comment]
It seems to be problem with the upm-xrremote.apk from [](https://github.com/youar/upm-xrremote/releases)

1. Import sample scenes in Package Manager and open the AR Remote Server scene.
2. Note the Ar Pose Driver field on the XR Remote server component of the XR Remote Server object is set to None.
3. Open the AR Session Origin > AR Camera object, remove the Tracked Pose Driver component and add the AR Pose Driver component.
4. Back in the XR Remote Server object, drag the AR Camera object to the Ar Pose Driver field to set the reference.
5. In the Build settings, add the AR Remote Server scene to the build list.  Then Build and Run on phone.
6.  Open the AR Remote Client scene and play in Unity.  Now I am able to see the camera stream from the phone in Unity.

![Screenshot 2023-03-14 121041](https://user-images.githubusercontent.com/67300046/225127391-4dcdb790-05ef-478d-bf70-ae1aa18ca404.jpg)
![Screenshot 2023-03-14 121112](https://user-images.githubusercontent.com/67300046/225127408-f8802c12-e3d7-4dd0-9f2a-fd36a7bcf8c7.jpg)

**Comment by gblikas** [comment]
Closing. Solved by #29 and https://github.com/youar/upm-xrremote/tree/staging
