### ISSUE TITLE
FPS Optimization

### ISSUE THREAD

**Issue by AsheUrban** [youar/upm-xrremote#25]
<ins>Is your feature request related to a problem? Please describe.</ins>

Image frame rate rendered in unity is underperforming and has a large potential for improvement, with deserialization and serialization consuming the most processing time at 60ms.

<ins>Describe the solution you'd like</ins>

The goal is to optimize frame rate to 15 FPS.

<ins>Describe alternatives you've considered</ins>

**Rewrite deserialization and serialization scripts:**
Rather than using prebuilt methods, identify alternative solutions by writing custom  
            methods.

**[Implement Unity NDI](https://chat.openai.com/share/dd6b5e8f-0992-422e-aab2-95186abdbea4):**
A plugin to handle video streaming, including deserialization and serialization.
- Would require updates to both server side and client side applications/code
- Note: There is no MKV format option for NDI

**[Implement ZeroFormatter](https://chat.openai.com/share/52614d9f-ebdf-4450-8e58-18ee3a781da6):**
A serialization library for .NET applications. It is designed to optimize the serialization and deserialization process, aiming for high performance and compact data representation.

<ins>Additional context</ins>

[Microsoft Binary Formatter](https://chat.openai.com/share/e76b9ef2-ef7b-46f9-ad6b-384a8e61a5c0) is a built-in serialization mechanism provided by the .NET framework. Is it currently being used in project.

Code was originally adopted from this [StackOverflow thread](https://stackoverflow.com/questions/1446547/how-to-convert-an-object-to-a-byte-array-in-c-sharp).

Potential Resources:
[ZeroFormatter — Fastest C# Serializer and Infinitely Fast Deserializer for .NET, .NET Core and Unity](https://neuecc.medium.com/zeroformatter-fastest-c-serializer-and-infinitely-fast-deserializer-for-net-88e752803fe9)
[ZeroFormatter ChatGPT Conversation](https://chat.openai.com/share/52614d9f-ebdf-4450-8e58-18ee3a781da6)
[Overarching AI Conversation](https://chat.openai.com/share/0451f604-285e-4b7f-9c1f-10979f7551ea) (includes potential notes on shader improvements)

**Comment by gblikas** [comment]
@AsheUrban I totally dig the ChatGPT summary info; really helpful to get caught up with where ya’ll are at 👍🏼 

I would consider implementing NDI, first. I haven’t read the docs (fill me in if this is the case), but I’d assume that NDI does something along the lines of what ChatGPT mentions with 
>
> GPU instancing: Utilize GPU instancing to render multiple instances of the same object with a single draw call. This technique significantly reduces CPU overhead and improves rendering performance.
>

Also, 
>
> Would require updates to both server side and client side applications/code
> 

is fine if the release includes it.
