### ISSUE TITLE
Add support for multiple video destination cameras

### ISSUE THREAD

**Issue by CarlSustrich** [youar/upm-xrremote#33]
**Is your feature request related to a problem? Please describe.**
Many user scenarios may possess more than one ARCamera, and enable or disable them as part of component lifecycles. 

**Describe the solution you'd like**
Add ability to create a list of camera references to the client receiver, comprising the possible video output destinations. Add check in the update cycle so it switches it's output to only the active camera of the list. 

**Describe alternatives you've considered**
Add support for multiple client receivers, and have them only function when their associated camera is active/enabled.

**Comment by gblikas** [comment]
Closed by #36 - [25d0c93](https://github.com/youar/upm-xrremote/pull/36/commits/25d0c93dadf96aada394f370631f0e0db3a0b30d)
