### ISSUE TITLE
Version testing required

### ISSUE THREAD

**Issue by Json-x-ly** [youar/upm-xrremote#4]
Current implementation has only been tested and designed for Unity 2020.3.x paired with ARFoundation 4.1.x. 

There is a higher degree of confidence in the current implementation working as early as Unity 2019.4.x since that is the currently supported version as of ARFoundation 4.1.x according to:
https://docs.unity3d.com/Packages/com.unity.xr.arfoundation@4.1/manual/index.html

In addition, since the early implementations of this package use the `TrackedPoseDriver` as the only major interface into the XR systems, it could potentially work as far back in Unity 2019.1.x | `RFoundation 1.x

**Comment by nickvachara** [comment]
Tested the upm in the following Unity3D Versions with the following AR Foundation version
`Pose Data` refers to the ability to see device's position and rotation reflect in Unity Editor
`AR Background` refers to the ability to see the device's view in Unity Editor

Note:
cannot use AR Foundation lower than `4.0.2` results in `Nullreference` 
if using AR Foundation `4.0.2` - `4.1.9` user has to manually set Camera as `MainCamera`

| Unity3D Vers | AR Foundation vers | Pose Data | AR Background |
| -------------- | ---------------------- | ---------- | -----------------|
| 2019.4.24f1  |	4.1.10	| ✔️ | ✔️ |
| 2019.4.28f1  |	 4.1.10| ✔️ | ✔️ |
| 2019.4.40f1  |	 4.1.10| ✔️ | ✔️ |
| 2020.3.20f1  |	 4.1.12| ✔️ | ✔️ |
| 2020.3.38f1  |	 4.1.13| ✔️ | ✔️ |
| 2020.3.41f1  |	 4.1.13| ✔️ | ✔️ |
| 2021.3.8f1    |	 4.2.3| ✔️ | ✔️ |
| 2022.1.17f1  |	 4.2.3| ✔️ | ✔️ |
