### ISSUE TITLE
Plane tag and Debug tags are annoying to setup 

### ISSUE THREAD

**Issue by gblikas** [youar/upm-xrremote#40]
**Is your feature request related to a problem? Please describe.**
As a part of our setup process, we "need" to add a `Plane` and `XRRemote-Debug` Tag in order for those systems to appear on editor. It would be ideal to have a Editor script that does this dynamically. 

**Describe alternatives you've considered**
There might be something in Unity Package system that would allow us to specify tags that get added, outside of Editor scripting.

**Comment by Razieleron** [comment]
there are multiple ways we can go about this, I believe.  this is one package I found: 
https://github.com/IntoTheDev/MultiTag-System-for-Unity

Some things to think about - in the version of unity we're using (2021.3), there are two issues that might need addressed - 
[Tags - Unity Documentation]
(https://docs.unity3d.com/2021.3/Documentation/Manual/Tags.html)
Once you name a tag, it can’t be renamed later.
A GameObject can only have one tag assigned to it.
